# Generated by Django 6.0.4 on 2026-04-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Adresi')),
                ('host', models.CharField(max_length=255, verbose_name='Erişilen Host (Subdomain)')),
                ('path', models.CharField(max_length=500, verbose_name='Gidilen Sayfa')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='Tarayıcı Bilgisi')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Erişim Tarihi')),
            ],
            options={
                'verbose_name': 'Ziyaretçi IP',
                'verbose_name_plural': 'Ziyaretçi IP Kayıtları',
                'ordering': ['-timestamp'],
            },
        ),
    ]
