# Generated by Django 6.0.4 on 2026-04-28 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IsletmeProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isletme_adi', models.CharField(max_length=200, verbose_name='İşletme Adı')),
                ('telefon', models.CharField(max_length=15, verbose_name='Telefon Numarası')),
                ('sektor', models.CharField(choices=[('YEMEK', 'Yemek & Restoran'), ('MARKET', 'Market & Bakkal'), ('ECZANE', 'Eczane'), ('GIYIM', 'Giyim & Moda'), ('ELEKTRONIK', 'Elektronik'), ('KOZMETIK', 'Kozmetik & Kişisel Bakım'), ('KITAP', 'Kitap & Kırtasiye'), ('DIGER', 'Diğer')], default='DIGER', max_length=30, verbose_name='Sektör')),
                ('adres', models.TextField(verbose_name='Açık Adres')),
                ('il', models.CharField(blank=True, default='', max_length=50, verbose_name='İl')),
                ('ilce', models.CharField(blank=True, default='', max_length=50, verbose_name='İlçe')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Enlem')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Boylam')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'ISLETME'}, on_delete=django.db.models.deletion.CASCADE, related_name='isletme_profil', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'İşletme Profili',
                'verbose_name_plural': 'İşletme Profilleri',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
    ]
