# Generated by Django 6.0.4 on 2026-04-28 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KuryeProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anlik_enlem', models.FloatField(default=0.0)),
                ('anlik_boylam', models.FloatField(default=0.0)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_kurye', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isletme_enlem', models.FloatField()),
                ('isletme_boylam', models.FloatField()),
                ('musteri_enlem', models.FloatField()),
                ('musteri_boylam', models.FloatField()),
                ('durum', models.CharField(choices=[('Beklemede', 'Beklemede'), ('Kurye Atandı', 'Kurye Atandı'), ('Yolda', 'Yolda'), ('Teslim Edildi', 'Teslim Edildi')], default='Beklemede', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kurye', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo_app.kuryeprofil')),
            ],
        ),
    ]
